export const seriesData = [
  {
    slug: 'womb-journey',
    title: 'Womb Journey',
    desc: 'Exploring the genesis of creation and the protective energy.',
    fullDesc: 'A descent into the sacred, where creation begins in the quiet darkness. The womb holds the mystery of life unfolding—a sanctuary of warmth, renewal, and infinite potential. Through the sacred umbilical thread, it reaches into the lineage of the feminine.',
  },
  {
    slug: 'sacred-feminine',
    title: 'Sacred Feminine',
    desc: 'Awakening the primal, nurturing, and powerful feminine essence.',
    fullDesc: 'The Sacred Feminine is the eternal healer, the essence that transcends time and form, mending the fractures of existence with her boundless grace. This series invites you to experience her essence—a journey into the infinite, where art becomes a reflection of her divine rhythm and timeless grace.',
  },
  {
    slug: 'soul-evolution',
    title: 'Soul Evolution',
    desc: 'Visualizing the spiritual ascension and untangling of the self.',
    fullDesc: 'Soul Evolution is a journey through sacred cycles, where the soul, deeply connected with the divine, embarks on a path of transformation. In its purest state, it exists in unity with the cosmos, expanding in light and wisdom to honor the harmony between spirit and form.',
  }
];

export const artworksData = [
  {
    slug: 'chromatic-symphony',
    title: 'Chromatic Symphony',
    series: 'womb-journey',
    seriesTitle: 'Womb Journey',
    medium: 'Acrylic on Canvas',
    size: '152 x 152 cm',
    quote: 'In the grand symphony of creation, She is both witness and vessel...',
    image: '/placeholder-1.jpg',
    color: 'from-orange-900 to-red-900',
  },
  {
    slug: 'divine-alignment',
    title: 'Divine Alignment',
    series: 'womb-journey',
    seriesTitle: 'Womb Journey',
    medium: 'Acrylic on Canvas',
    size: '123 x 123 cm',
    quote: 'In the quiet vastness of becoming, the soul meets its purpose...',
    image: '/placeholder-2.jpg',
    color: 'from-green-900 to-emerald-900',
  },
  {
    slug: 'purifying-flame',
    title: 'The Purifying Flame',
    series: 'sacred-feminine',
    seriesTitle: 'Sacred Feminine',
    medium: 'Acrylic on Canvas',
    size: '122 x 91 cm',
    quote: 'The journey begins with an awakening—a realization that to rise above herself, she must release all that holds her to the realm of the self.',
    image: '/placeholder-3.jpg',
    color: 'from-fuchsia-900 to-rose-900',
  },
  {
    slug: 'sacred-rebirth',
    title: 'Sacred Rebirth',
    series: 'womb-journey',
    seriesTitle: 'Womb Journey',
    medium: 'Acrylic on Canvas',
    size: '160 x 81 cm',
    quote: 'In the sacred act of rebirth, cosmic mother’s energies converge, forging the soul anew through a journey of release and renewal.',
    image: '/placeholder-4.jpg',
    color: 'from-red-900 to-amber-900',
  },
  {
    slug: 'flow-of-origins',
    title: 'Flow of Origins',
    series: 'soul-evolution',
    seriesTitle: 'Soul Evolution',
    medium: 'Acrylic on Canvas',
    size: '180 x 120 cm',
    quote: 'In the beginning, the soul immerses itself in the elemental embrace of water, where the essence of life stirs gently into motion.',
    image: '/placeholder-5.jpg',
    color: 'from-blue-900 to-cyan-900',
  },
  {
    slug: 'eternal-resonance',
    title: 'Eternal Resonance',
    series: 'soul-evolution',
    seriesTitle: 'Soul Evolution',
    medium: 'Acrylic on Canvas',
    size: '122 x 97 cm',
    quote: 'In this evolving cycle, the soul rejoins the vast symphony of cosmic frequencies, flowing endlessly through realms of existence.',
    image: '/placeholder-6.jpg',
    color: 'from-indigo-900 to-violet-900',
  }
];
